### ISSUE TITLE
panic: invalid character 'a' looking for beginning of value

### ISSUE THREAD

**Issue by BrownMikaelson** [HydroProtocol/hydro-box-dex#88]
`hydro-dex-ctl market new CVRL-WETH \
  --baseTokenAddress=0x448C0a7fb16D8CA04D1142D4D12D61672697B173 \
  --quoteTokenAddress=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
`

![help](https://user-images.githubusercontent.com/50189679/92336625-e9f34f00-f078-11ea-98a5-2e34112d6d56.png)

 **1 - I'm not able to add new pairs** 

**erro: panic: invalid character 'a' looking for beginning of value**

```
 panic: invalid character 'a' looking for beginning of value

goroutine 1 [running]:
github.com/HydroProtocol/hydro-sdk-backend/sdk/ethereum.callContract(0xc00000e02
0, 0xc000014240, 0x2a, 0x992a3c, 0xa, 0xc0000ac960, 0x4dffd3)
        /go/pkg/mod/github.com/!hydro!protocol/hydro-sdk-backend@v0.0.41/sdk/eth
ereum/erc20.go:217 +0x148
github.com/HydroProtocol/hydro-sdk-backend/sdk/ethereum.(*Erc20Service).Symbol(0
xc00000e020, 0xc000014240, 0x2a, 0x2a, 0x1, 0x0, 0x7f871b717000)
        /go/pkg/mod/github.com/!hydro!protocol/hydro-sdk-backend@v0.0.41/sdk/eth
ereum/erc20.go:86 +0x5e
github.com/HydroProtocol/hydro-scaffold-dex/backend/admin/cli.(*Admin).NewMarket
(0xc0004f0000, 0x7ffc813e1c88, 0x9, 0xc000014240, 0x2a, 0x7ffc813e1ce4, 0x2a, 0x
0, 0x0, 0x0, ...)
        /app/admin/cli/admin.go:119 +0xd6
github.com/HydroProtocol/hydro-scaffold-dex/backend/admin/cli.NewDexCli.func2(0x
c0004de420, 0xb2b900, 0x33)
        /app/admin/cli/cli.go:193 +0x233
github.com/urfave/cli.HandleAction(0x8f81c0, 0xc0004fa000, 0xc0004de420, 0xc0000
10100, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x99043a, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x994a
00, 0xf, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9a2
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0004da340, 0xc0004de160, 0x0, 0x
0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:379 +0x7ef
github.com/urfave/cli.Command.startApp(0x991449, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0
x99dbb4, 0x20, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:298 +0x808
github.com/urfave/cli.Command.Run(0x991449, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x99db
b4, 0x20, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:98 +0x1250
github.com/urfave/cli.(*App).Run(0xc0004da1a0, 0xc000066180, 0x6, 0x6, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x687
main.main()
        /app/cli/admincli/main.go:12 +0x4f

```
 
**2 - How to remove pairs**
**3 - How to receive all tx fee in my admin wallet?**

**Comment by spanishvelas** [comment]
Same error here, can add pairs in mainnet.
**hydro-dex-ctl market new HOT-BAT --baseTokenAddress=0x4c4fa7e8ea4cfcfc93deae2c0cff142a1dd3a218 --quoteTokenAddress=0x0D8775F648430679A709E98d2b0Cb6250d2887EF
panic: invalid character 'a' looking for beginning of value**
